### ISSUE TITLE
Output DNA sequence shorter than input

### ISSUE THREAD

**Issue by doorholez** [timkartar/DeepPBS#14]
Hi,
Thanks a lot for sharing such an excellent work! I'm currenly working on a project with your work. But I met a problem that some of the output DNA sequences are shorter than input sequence. The problem appears quite frequently (92 out of 335 preditions) and it can be reproduced with the same pdb file. I used RF2NA to predict a structure and take the predicted pdb file as the input of DeepPBS.
Is this a designed feature or a bug working with RF2NA? Can I get a DNA sequence with the same length of input?

**Comment by timkartar** [comment]
Hi ! Thanks for your comment and question ! It's not a bug and working as intended. The reason it may be shorter is because the pre processing for deeppbs doesn't detect the end region as a helical region. 

Your options are :

1. Add flanking DNA sequences (e.g. GCGC on either side of your intended core, you can ignore predictions on them). I recommend this. 
2. Try something else like AF3 to see if it folds it in a helix correctly. But it could still fail to do so.

**Comment by doorholez** [comment]
Thanks a lot for your quick and kind response! I will try your advices!
